site_name: 'NadekoBot'
site_url: 'https://nadeko.bot'
repo_url: 'https://gitlab.com/kwoth/nadekobot'
site_author: 'Kwoth'

theme:
    name: material
    custom_dir: docs/overrides
    palette:
          - media: "(prefers-color-scheme: light)"
            scheme: default
            primary: blue
            accent: light blue
            toggle:
                icon: material/weather-sunny
                name: Switch to dark mode
          - media: "(prefers-color-scheme: dark)"
            scheme: dark
            primary: blue
            accent: light blue
            toggle:
                icon: material/weather-night
                name: Switch to light mode
    features:
        - navigation.instant
        - navigation.expand
        - navigation.top
    font: 
        text: Source Sans Pro
        code: Source Code Pro
    logo: assets/favicon.png
    favicon: assets/favicon.png
    icon: 
        repo: custom/gitlab

extra:
  homepage: https://nadeko.bot

extra_css:
  - stylesheets/styling-overrides.css
  - stylesheets/theme.css

plugins:
    - git-revision-date-localized:
        type: date
    - search

markdown_extensions:
    - attr_list
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.betterem:
        smart_enable: all
    - admonition
    - meta
    - footnotes
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
            custom_icons:
                - docs/overrides/.icons

nav:
    - Home: index.md
    - Guides:
        - Windows Guide: guides/windows-guide.md
        - Linux Guide: guides/linux-guide.md
        - OSX Guide: guides/osx-guide.md
        - From Source: guides/from-source.md
        - Docker Guide (unsupported): guides/docker-guide.md
    - Commands:
        - Readme: commands-readme.md
        - Commands List: https://nadeko.bot/commands
    - Features Explained:
        - Creating and inviting the bot: create-invite.md
        - Credentials & API Keys: jsons-explained.md
        - Permissions System: permissions-system.md
        - Custom Reactions: custom-reactions.md
        - Placeholders: placeholders.md
        - Config: config-guide.md
        - Bot Config: bce-guide.md
    - Contribution Guide: contribution-guide.md
    - Donate: donate.md
    - License: license.md
