version: "3.5"

services:
  nadeko:
    image: ghcr.io/gibstick/nadekobot_fork:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./credentials.json:/home/nadeko/app/credentials.json:ro
      - nadeko-data:/home/nadeko/app/data
      - nadeko-db:/home/nadeko/app/db/
    environment:
      NadekoBot_RedisOptions: redis,name=nadeko
      NadekoBot_ShardRunCommand: dotnet
      NadekoBot_ShardRunArguments: NadekoBot.dll {0} {1}
      NadekoBot_Db__Type: sqlite
      NadekoBot_Db__ConnectionString: "Data Source=db/nadekobot.db"

  redis:
    image: redis:alpine
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: 511

volumes:
  nadeko-data:
    external: true
  nadeko-db:
    external: true
